jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install Android SDK
      run: |
        mkdir -p $HOME/android-sdk
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O tools.zip
        unzip -q tools.zip -d $HOME/android-sdk
        rm tools.zip
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --update
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "build-tools;33.0.0"
        
    - name: Create directories for symbolic link
      run: |
        mkdir -p /usr/local/android-sdk/platforms

    - name: Create symbolic link for android-33
      run: |
        ln -s $HOME/android-sdk/platforms/android-33 /usr/local/android-sdk/platforms/android-33

    - name: Restore NuGet packages
      run: dotnet restore WoWonder.sln

    - name: Build APK
      run: dotnet build WoWonder.sln -c Release /p:AndroidSdkDirectory=$HOME/android-sdk
