name: Build Xamarin Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET SDK 7.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Install Android Workload
        run: dotnet workload install android

      - name: Install JDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk

      - name: Install Android SDK Command Line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          cd $HOME/android-sdk/cmdline-tools/latest
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip
          rm -f commandlinetools-linux-8512546_latest.zip
          mv cmdline-tools/* . 
          rm -rf cmdline-tools

      - name: Set environment variables
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: Install Android SDK Packages
        run: |
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "build-tools;33.0.0" "platform-tools"

      - name: Restore NuGet packages
        run: dotnet restore WoWonder.sln

      - name: Build APK and AAB
        run: |
          dotnet build WoWonder.sln -c Release /p:AndroidSdkDirectory=$HOME/android-sdk
          msbuild /p:Configuration=Release /p:AndroidPackageFormat=aab WoWonder/WoWonder.csproj /p:AndroidSdkDirectory=$HOME/android-sdk
          msbuild /p:Configuration=Release /p:AndroidPackageFormat=apk WoWonder/WoWonder.csproj /p:AndroidSdkDirectory=$HOME/android-sdk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: path/to/your/Release/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: aab
          path: path/to/your/Release/*.aab
