name: Build Xamarin Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET SDK 7.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Install Android Workload for .NET 7
        run: dotnet workload install android

      - name: Install JDK
        run: sudo apt-get install -y openjdk-11-jdk

      - name: Install Android SDK Command Line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          cd $HOME/android-sdk/cmdline-tools/latest
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip
          rm -f commandlinetools-linux-8512546_latest.zip
          mv cmdline-tools/* . 
          rm -rf cmdline-tools
          ls -l $HOME/android-sdk/cmdline-tools/latest/bin 

      - name: Set Android SDK path
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV

      - name: Accept Android SDK licenses
        run: yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install SDK Packages
        run: $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "build-tools;33.0.0"

      - name: Restore NuGet packages
        run: dotnet restore WoWonder.sln

      - name: Build APK
        run: dotnet build WoWonder.sln -c Release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: path/to/your/Release/*.apk
