name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install .NET workloads
      run: |
        dotnet workload restore
        dotnet workload install android

    - name: Install Android SDK
      run: |
        # Create directory for Android SDK
        mkdir -p $HOME/android-sdk/cmdline-tools

        # Download and install command line tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O tools.zip
        unzip -q tools.zip -d $HOME/android-sdk/cmdline-tools
        rm tools.zip

        # Create 'latest' directory to match SDK Manager's expected path
        mkdir -p $HOME/android-sdk/cmdline-tools/latest

        # Move extracted files to 'latest' directory, avoiding self-reference
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/

        # Remove the now-empty original directory
        rmdir $HOME/android-sdk/cmdline-tools/cmdline-tools

        # Debug: List directory contents
        ls -la $HOME/android-sdk/cmdline-tools/latest/bin

        # Accept licenses and install required components
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --update
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "build-tools;33.0.0"

    - name: Restore NuGet packages
      run: dotnet restore WoWonder.sln
